type OneOrMore = string | Array<string>

interface ApprovalConfig {
  /**
   * Name of the content review. (n.b.: I don't know what this means!
   *
   * Within any {state} macro, each {approval} macro must be given a unique name
   *
   * The name can use any character set supported by your Confluence server – except some reserved characters.
   */
  unnamed: string;
  
  /**
   * The description for the approvals
   */
  description: string;
  
  /**
   Requires that the content has the specified label for the approval to be active.
   
   Only one label can be used
   
   The label cannot contain , !, #, &, (, ), *, ,, ., :, ;, <, >, ?, @, [, ], ^
   
   The label cannot be negated
   
   If the content does not have the specified label:
   
   - the Approve/Reject buttons are disabled.
   - reviewers cannot be manually assigned to the approval if the approval includes assignable=true
   - if the approval is one of several approvals in a state (multiple reviews) it is not required for the transition
   - If the addition of the specified label is a requirement for the the approval to be undertaken then use the haslabel condition instead. See: Conditions.
   */
  label: string;
  
  /*
  Conditions
  
  Optionally define additional requirements which must be met prior to content approval – see: Conditions.
    
    If one or more conditions are not met, the Approve/Reject buttons will be disabled. However, reviewer assignment will still be possible.
  */
  
  /* MORE INFO ABOUT THIS SECTION
  Reviewers / Assignees
  Specify if, who and how reviewers are assigned to the content review.
  
  † Parameters selectedapprover, selectedapprovers and (group and/or user) are mutually exclusive. You can use the parameters group and user together.
  
  ‡ Prefixing the list with & (ampersand) will auto-assign all users and require them to review (this feature is incompatible with the assignable parameter).
  
  
  If there are 15 or fewer possible assignees (as specified by the user, group, selectedapprover or selectedapprovers parameters, then they will all be listed by default on the Assigning reviewers screen without the need to perform a search.
  */
  
  /** Can the user assign reviewers?
   
   Note: Assignees must have permission to edit the content and also be member of confluence-users group as a minimum. Other parameters relating to reviewers may enforce further restrictions.*/
  assignable: boolean;
  
  /** To what extent do reviewers need to confirm their identity when reviewing?
   - 0: must be logged in (member of confluence-users group)
   - 1: additionally, must confirm Password / Signing Token
   - 2: additionally, must confirm Username
   
   The requirements stack, so a value of 2 would mean: Logged in + Password / Signing Token + Username.
   
   The method of authentication can be configured globally. The options above for the credential password can be set to be based on either:
   - a user's Confluence credentials
   - a signing token generated by a third-party app.*/
  credentials: number;
  
  /** List users who are not allowed to review.
   
   A comma-separated list of usernames.
   
   Supports Value References (for example: @author@ to prevent content author from reviewing)
   
   Note: While excluded users are not able to be assigned or Approve/Reject, they can still assign other users as reviewers where applicable (eg. if the assignable=true is used).*/
  exclude: OneOrMore;
  
  /** Reviewers must be a member of the specified user group(s):
   
   A comma-separated list of group names
   
   Supports Value References
   
   Note: Users who do not have Edit content permission will not be allowed to review.*/
  group: OneOrMore;
  
  /**
   Define the minimum number of reviewers required for the content review to be approved.
   
   Number ≥ 0
   
   Supports Value References (v4.18+)
   
   If using the selectedapprover or selectedapprovers parameters, the minimum defaults to 1.
   */
  minimum: number;
  
  /** Remember the assignees for reviews with this name?
   
   - true: any subsequent reviews in the workflow that have the same name as this review (as defined by unnamed
   first parameter) will automatically have the same reviewers assigned ("sticky assignees")
   - false: don't remember assignees
   */
  rememberassignees: boolean;
  
  /**  Enable approval roles feature
   - true: approval roles are enabled, users assigning a review will be able to record the role that the reviewer is
   performing
   - false: approval roles are disabled
   */
  roles: boolean;
  
  /** A comma-separated list of usernames and/or group names
   Group names are treated as "a list of usernames"
   
   Supports Value References
   
   Note: Users who do not have Edit content permission will not be allowed to review.
   */
  selectedapprover: OneOrMore;
  
  /** One or more reviewers must be assigned from the list:
   
   Group names are treated as "a list of usernames"
   
   Supports Value References
   
   Note: Users who do not have Edit content permission will not be allowed to review.
   */
  selectedapprovers: OneOrMore;
  
  /** Reviewers must be in the specified list:
   
   A comma-separated list of usernames‡
   
   Supports Value References
   
   Note: Users who do not have Edit content permission will not be allowed to review.
   */
  user: OneOrMore;
  
  /** Assigners must be in the specified list:
   
   A comma-separated list of usernames‡
   
   Supports Value References
   
   Note:
   - Users who do not have Edit content permission will not be allowed to assign. It can be used along with the
   allowedassigngroups parameter.
   - Adding this parameter does not disable the review for users who have Edit content permission until a reviewer
   has been assigned. To prevent the review from being undertaken before assignment of a reviewer, use this
   parameter in conjunction with one of selectedapprover or selectedapprovers parameters.
   */
  allowedassignusers: OneOrMore;
  
  /**  Assigners must be a member of the specified user group(s):
   
   A comma-separated list of group names
   
   Supports Value References
   
   Note
   - Users who do not have Edit content permission will not be allowed to assign. It can be used along with the
   allowedassigngroups parameter.
   - Adding this parameter does not disable the review for users who have Edit content permission until a reviewer
   has been assigned. To prevent the review from being undertaken before assignment of a reviewer, use this parameter in conjunction with one of  selectedapprover or  selectedapprovers parameters.
   */
  allowedassigngroups: OneOrMore;
  
  /* ADD THESE TO THE API LATER

  User Interface
  These parameters are used to customise the user interface of the Workflow Popup.
  
  approvelabel
  Approve
  Set the caption of the Approve button.
  
  5.1+
  rejectlabel
  Reject
  Set the caption of the Reject button.
  
  5.1+
  weight
  
  
  
  40
  
  When using multiple {approval} macros inside a single {state}, you can use this parameter to set the initial display order.
  
  Number ≥ 1
Valid values in range of 1 → 232
For best results, use multiples of 40.
Items of the same weight will be ordered alphabetically A→Z
Completed reviews will bubble to the top of the list, in order of completion*/
}